version: '{branch}-{build}'
before_build:
- cmd: nuget restore Agiil.sln
build:
  verbosity: minimal
test:
  assemblies:
    except:
    - **\Agiil.Tests.Common.dll
    - **\Agiil.BDD.dll
    - **\Ploeh.AutoFixture.NUnit3.dll