environment:
  nodejs_version: "10.0"

version: '{branch}-{build}'

init:
  - cmd: git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: Tools\AppVeyor-install.bat
  
before_build:
  - cmd: cd ..

configuration: AppVeyorCI

build:
  project: Agiil.sln
  verbosity: normal

test:
  assemblies:
    except:
      - '**\Agiil.Tests.Common.dll'
      - '**\Agiil.BDD.dll'
      - '**\Ploeh.AutoFixture.NUnit3.dll'
      - '**\Agiil.Tests.BDD.dll'
    