version: '{branch}-{build}'
before_build:
- cmd: nuget restore Agiil.sln
build:
  verbosity: minimal
test_script:
- cmd: >-
    packages\NUnit.Console.3.0.0\tools\nunit3-console.exe `dir * /s /b | findstr Agiil\.Tests`