version: '{branch}-{build}'
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: >-
  nuget restore Agiil.sln

  git submodule update --init --recursive
# As of 2017-05-15 it appears AppVeyor use a 32-bit MSBuild.
# This means that we must compile for 32-bit, because otherwise
# the custom 'CompileScssFiles' target will fail on usage of the
# 64-bit flavour of libsass.dll
platform: x86
build:
  verbosity: normal
test:
  assemblies:
    except:
    - '**\Agiil.Tests.Common.dll'
    - '**\Agiil.BDD.dll'
    - '**\Ploeh.AutoFixture.NUnit3.dll'