version: '{branch}-{build}'
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: nuget restore Agiil.sln
build:
  verbosity: normal
test:
  assemblies:
    except:
    - '**\Agiil.Tests.Common.dll'
    - '**\Agiil.BDD.dll'
    - '**\Ploeh.AutoFixture.NUnit3.dll'