image: Visual Studio 2017

environment:
  nodejs_version: "10.0"

version: '{branch}-{build}'

init:
  - cmd: git config --global core.autocrlf true

# Beware that using a batch file to contain many of the scripts (below)
# does not work.  The `npm install` commands cause the script to
# terminate early and abort any further execution.

install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init --recursive
  - choco install "sonarscanner-msbuild-net46" -y
  - nuget install -OutputDirectory %APPVEYOR_BUILD_FOLDER%\.OpenCover -Version 4.7.922 OpenCover

configuration: AppVeyorCI

before_build:
  - nuget restore Agiil.sln
  - cd Agiil.Web
  - npm install
  - cd ..
  - cd Agiil.Web.Client
  - npm install
  - cd ..
  - SonarScanner.MSBuild.exe begin /k:"Agiil" /v:AppVeyor_build_%APPVEYOR_BUILD_NUMBER% /s:%APPVEYOR_BUILD_FOLDER%\.sonarqube-analysisproperties.xml /o:craigfowler-github /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%SONARCLOUD_SECRET_KEY% /d:sonar.cs.nunit.reportsPaths=%APPVEYOR_BUILD_FOLDER%\Tests\Temp\TestResult.unit-tests.xml /d:sonar.cs.opencover.reportsPaths=%APPVEYOR_BUILD_FOLDER%\OpenCover.xml

build_script:
  - msbuild /verbosity:normal "Agiil.sln" /p:Configuration=AppVeyorCI

test_script:
  - .OpenCover\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:.\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe -targetargs:"--result=%APPVEYOR_BUILD_FOLDER%\Tests\Temp\TestResult.unit-tests.xml Tests\Agiil.Tests.Auth\bin\Debug\Agiil.Tests.Auth.dll Tests\Agiil.Tests.Data\bin\Debug\Agiil.Tests.Data.dll Tests\Agiil.Tests.Domain\bin\Debug\Agiil.Tests.Services.dll Tests\Agiil.Tests.Web\bin\Debug\Agiil.Tests.Web.dll" -output:%APPVEYOR_BUILD_FOLDER%\OpenCover.xml -filter:"+[Agiil.*]* -[Agiil.Tests.*]* -[Agiil.BDD]* -[Agiil.Web.TestBuild]* -[Agiil.Web.Client]* -[Agiil.QueryLanguage.Antlr]* -[Agiil.Bootstrap]* -[Agiil.Web.Models]*"

after_test:
  - SonarScanner.MSBuild.exe end /d:"sonar.login=%SONARCLOUD_SECRET_KEY%"

artifacts:
  - path: OpenCover.xml
  - path: Tests\Temp\TestResult.unit-tests.xml