image: Visual Studio 2017

environment:
  nodejs_version: "10.0"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk13"
  nunit_console_version: "3.7.0"
  opencover_version: "4.7.922"

version: '{branch}-{build}'

init:
  - cmd: git config --global core.autocrlf true

install: powershell.exe -file Tools\AppVeyor-install.ps1

build_script: powershell.exe -file Tools\AppVeyor-build.ps1

test_script:
  - echo "Tests already run as part of build"