sudo: false
language: csharp
solution: Agiil.sln
  
addons:
  sauce_connect: true
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb https://deb.nodesource.com/node_10.x trusty main'
        key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    packages:
      - mono-xsp4
      - libstdc++6-4.7-dev
      - nodejs

matrix:
  include:
    - env:
      - WebDriver_Platform="Windows 10"
      - WebDriver_BrowserName="Chrome"
      - WebDriver_BrowserVersion="56.0"
    - env:
      - WebDriver_Platform="Windows 10"
      - WebDriver_BrowserName="Firefox"
      - WebDriver_BrowserVersion="53.0"
    - env:
      - WebDriver_Platform="Windows 7"
      - WebDriver_BrowserName="Internet Explorer"
      - WebDriver_BrowserVersion="11.0"
    - env:
      - WebDriver_Platform="Windows 7"
      - WebDriver_BrowserName="Internet Explorer"
      - WebDriver_BrowserVersion="9.0"
# TODO: #AG66 - Reinstate testing in Edge once problems are fixed
#     - env:
#       - WebDriver_Platform="Windows 10"
#       - WebDriver_BrowserName="MicrosoftEdge"
#       - WebDriver_BrowserVersion="16.16299"
    - env:
      - WebDriver_Platform="OS X 10.11"
      - WebDriver_BrowserName="Safari"
      - WebDriver_BrowserVersion="10.0"

install: ./Tools/Travis-install.sh

script: ./Tools/Travis-build.sh  
