language: csharp
solution: Agiil.sln

install:
  - mkdir -p ~/.mono
  - cp Tools/mono.config ~/.mono/config
  - nuget restore Agiil.sln
  - nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Debug Agiil.sln
  - ls -l Tests/Agiil.Tests.Web.Sass/bin/Debug
  - MONO_LOG_LEVEL=debug mono "./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe" $(find ./Tests/ -type f -path "*/bin/Debug/*" -name "Agiil.Tests*.dll" \! -name "Agiil.Tests.Common.dll")