SET SCRIPT_PATH=%~dp0
SET ANTLR_JAR_PATH=%SCRIPT_PATH%..\lib
SET SOURCE_PATH=%SCRIPT_PATH%\..\Grammar
SET CUSTOM_CLASSPATH=.:%ANTLR_JAR_PATH%\antlr-4.7.1-complete.jar:%SOURCE_PATH%:%CLASSPATH%

java -cp %CUSTOM_CLASSPATH% org.antlr.v4.gui.TestRig %*