//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/craig/Projects/Agiil/Agiil.QueryLanguage.Antlr/AgiilQuery.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Agiil.QueryLanguage {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class AgiilQueryParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BOM=1, OPENPAREN=2, CLOSEPAREN=3, EQUALS=4, NOTEQUALS=5, TILDE=6, COMMA=7, 
		DOUBLEQUOTE=8, GREATERTHAN=9, LESSTHAN=10, GREATERTHANOREQUAL=11, LESSTHANOREQUAL=12, 
		WHITESPACE=13, NOT=14, AND=15, OR=16, ORDERBY=17, DESCENDING=18, ASCENDING=19, 
		NAME=20, WORD=21, QUOTEDVALUE=22, ANY=23;
	public const int
		RULE_search = 0, RULE_criteria = 1, RULE_logicalcriteriagroups = 2, RULE_criterionorgroup = 3, 
		RULE_criteriagroup = 4, RULE_criterion = 5, RULE_elementtest = 6, RULE_logicaloperator = 7, 
		RULE_element = 8, RULE_predicate = 9, RULE_predicatename = 10, RULE_comparison = 11, 
		RULE_value = 12, RULE_constantvalue = 13, RULE_functioninvocation = 14, 
		RULE_functionparameters = 15, RULE_orders = 16, RULE_orderelement = 17;
	public static readonly string[] ruleNames = {
		"search", "criteria", "logicalcriteriagroups", "criterionorgroup", "criteriagroup", 
		"criterion", "elementtest", "logicaloperator", "element", "predicate", 
		"predicatename", "comparison", "value", "constantvalue", "functioninvocation", 
		"functionparameters", "orders", "orderelement"
	};

	private static readonly string[] _LiteralNames = {
		null, "'\uFEFF'", "'('", "')'", "'='", "'!='", "'~'", "','", "'\"'", "'>'", 
		"'<'", "'>='", "'<='"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BOM", "OPENPAREN", "CLOSEPAREN", "EQUALS", "NOTEQUALS", "TILDE", 
		"COMMA", "DOUBLEQUOTE", "GREATERTHAN", "LESSTHAN", "GREATERTHANOREQUAL", 
		"LESSTHANOREQUAL", "WHITESPACE", "NOT", "AND", "OR", "ORDERBY", "DESCENDING", 
		"ASCENDING", "NAME", "WORD", "QUOTEDVALUE", "ANY"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "AgiilQuery.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static AgiilQueryParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public AgiilQueryParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public AgiilQueryParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class SearchContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(AgiilQueryParser.Eof, 0); }
		public ITerminalNode BOM() { return GetToken(AgiilQueryParser.BOM, 0); }
		public CriteriaContext criteria() {
			return GetRuleContext<CriteriaContext>(0);
		}
		public OrdersContext orders() {
			return GetRuleContext<OrdersContext>(0);
		}
		public SearchContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_search; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSearch(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SearchContext search() {
		SearchContext _localctx = new SearchContext(Context, State);
		EnterRule(_localctx, 0, RULE_search);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 37;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==BOM) {
				{
				State = 36; Match(BOM);
				}
			}

			State = 40;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==OPENPAREN || _la==NAME) {
				{
				State = 39; criteria();
				}
			}

			State = 43;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ORDERBY) {
				{
				State = 42; orders();
				}
			}

			State = 45; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CriteriaContext : ParserRuleContext {
		public LogicalcriteriagroupsContext logicalcriteriagroups() {
			return GetRuleContext<LogicalcriteriagroupsContext>(0);
		}
		public CriteriaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_criteria; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCriteria(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CriteriaContext criteria() {
		CriteriaContext _localctx = new CriteriaContext(Context, State);
		EnterRule(_localctx, 2, RULE_criteria);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47; logicalcriteriagroups();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalcriteriagroupsContext : ParserRuleContext {
		public CriterionorgroupContext[] criterionorgroup() {
			return GetRuleContexts<CriterionorgroupContext>();
		}
		public CriterionorgroupContext criterionorgroup(int i) {
			return GetRuleContext<CriterionorgroupContext>(i);
		}
		public LogicaloperatorContext[] logicaloperator() {
			return GetRuleContexts<LogicaloperatorContext>();
		}
		public LogicaloperatorContext logicaloperator(int i) {
			return GetRuleContext<LogicaloperatorContext>(i);
		}
		public LogicalcriteriagroupsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalcriteriagroups; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalcriteriagroups(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalcriteriagroupsContext logicalcriteriagroups() {
		LogicalcriteriagroupsContext _localctx = new LogicalcriteriagroupsContext(Context, State);
		EnterRule(_localctx, 4, RULE_logicalcriteriagroups);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 49; criterionorgroup();
			State = 56;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OPENPAREN) | (1L << AND) | (1L << OR) | (1L << NAME))) != 0)) {
				{
				{
				State = 51;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AND || _la==OR) {
					{
					State = 50; logicaloperator();
					}
				}

				State = 53; criterionorgroup();
				}
				}
				State = 58;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CriterionorgroupContext : ParserRuleContext {
		public CriterionContext criterion() {
			return GetRuleContext<CriterionContext>(0);
		}
		public CriteriagroupContext criteriagroup() {
			return GetRuleContext<CriteriagroupContext>(0);
		}
		public CriterionorgroupContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_criterionorgroup; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCriterionorgroup(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CriterionorgroupContext criterionorgroup() {
		CriterionorgroupContext _localctx = new CriterionorgroupContext(Context, State);
		EnterRule(_localctx, 6, RULE_criterionorgroup);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NAME:
				{
				State = 59; criterion();
				}
				break;
			case OPENPAREN:
				{
				State = 60; criteriagroup();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CriteriagroupContext : ParserRuleContext {
		public ITerminalNode OPENPAREN() { return GetToken(AgiilQueryParser.OPENPAREN, 0); }
		public LogicalcriteriagroupsContext logicalcriteriagroups() {
			return GetRuleContext<LogicalcriteriagroupsContext>(0);
		}
		public ITerminalNode CLOSEPAREN() { return GetToken(AgiilQueryParser.CLOSEPAREN, 0); }
		public CriteriagroupContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_criteriagroup; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCriteriagroup(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CriteriagroupContext criteriagroup() {
		CriteriagroupContext _localctx = new CriteriagroupContext(Context, State);
		EnterRule(_localctx, 8, RULE_criteriagroup);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63; Match(OPENPAREN);
			State = 64; logicalcriteriagroups();
			State = 65; Match(CLOSEPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CriterionContext : ParserRuleContext {
		public ElementContext element() {
			return GetRuleContext<ElementContext>(0);
		}
		public ElementtestContext elementtest() {
			return GetRuleContext<ElementtestContext>(0);
		}
		public CriterionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_criterion; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCriterion(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CriterionContext criterion() {
		CriterionContext _localctx = new CriterionContext(Context, State);
		EnterRule(_localctx, 10, RULE_criterion);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67; element();
			State = 68; elementtest();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementtestContext : ParserRuleContext {
		public PredicateContext predicate() {
			return GetRuleContext<PredicateContext>(0);
		}
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public FunctioninvocationContext functioninvocation() {
			return GetRuleContext<FunctioninvocationContext>(0);
		}
		public ITerminalNode NOT() { return GetToken(AgiilQueryParser.NOT, 0); }
		public ElementtestContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elementtest; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElementtest(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementtestContext elementtest() {
		ElementtestContext _localctx = new ElementtestContext(Context, State);
		EnterRule(_localctx, 12, RULE_elementtest);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				{
				{
				State = 70; predicate();
				State = 71; value();
				}
				}
				break;
			case 2:
				{
				{
				State = 74;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==NOT) {
					{
					State = 73; Match(NOT);
					}
				}

				State = 76; functioninvocation();
				}
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicaloperatorContext : ParserRuleContext {
		public ITerminalNode AND() { return GetToken(AgiilQueryParser.AND, 0); }
		public ITerminalNode OR() { return GetToken(AgiilQueryParser.OR, 0); }
		public LogicaloperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicaloperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicaloperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicaloperatorContext logicaloperator() {
		LogicaloperatorContext _localctx = new LogicaloperatorContext(Context, State);
		EnterRule(_localctx, 14, RULE_logicaloperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			_la = TokenStream.LA(1);
			if ( !(_la==AND || _la==OR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElementContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(AgiilQueryParser.NAME, 0); }
		public ElementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_element; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElementContext element() {
		ElementContext _localctx = new ElementContext(Context, State);
		EnterRule(_localctx, 16, RULE_element);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81; Match(NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PredicateContext : ParserRuleContext {
		public PredicatenameContext predicatename() {
			return GetRuleContext<PredicatenameContext>(0);
		}
		public ITerminalNode NOT() { return GetToken(AgiilQueryParser.NOT, 0); }
		public PredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_predicate; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PredicateContext predicate() {
		PredicateContext _localctx = new PredicateContext(Context, State);
		EnterRule(_localctx, 18, RULE_predicate);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NOT) {
				{
				State = 83; Match(NOT);
				}
			}

			State = 86; predicatename();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PredicatenameContext : ParserRuleContext {
		public ITerminalNode EQUALS() { return GetToken(AgiilQueryParser.EQUALS, 0); }
		public ITerminalNode NOTEQUALS() { return GetToken(AgiilQueryParser.NOTEQUALS, 0); }
		public ITerminalNode TILDE() { return GetToken(AgiilQueryParser.TILDE, 0); }
		public ITerminalNode NAME() { return GetToken(AgiilQueryParser.NAME, 0); }
		public ComparisonContext comparison() {
			return GetRuleContext<ComparisonContext>(0);
		}
		public PredicatenameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_predicatename; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPredicatename(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PredicatenameContext predicatename() {
		PredicatenameContext _localctx = new PredicatenameContext(Context, State);
		EnterRule(_localctx, 20, RULE_predicatename);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case EQUALS:
				{
				State = 88; Match(EQUALS);
				}
				break;
			case NOTEQUALS:
				{
				State = 89; Match(NOTEQUALS);
				}
				break;
			case TILDE:
				{
				State = 90; Match(TILDE);
				}
				break;
			case NAME:
				{
				State = 91; Match(NAME);
				}
				break;
			case GREATERTHAN:
			case LESSTHAN:
			case GREATERTHANOREQUAL:
			case LESSTHANOREQUAL:
				{
				State = 92; comparison();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComparisonContext : ParserRuleContext {
		public ITerminalNode GREATERTHAN() { return GetToken(AgiilQueryParser.GREATERTHAN, 0); }
		public ITerminalNode LESSTHAN() { return GetToken(AgiilQueryParser.LESSTHAN, 0); }
		public ITerminalNode GREATERTHANOREQUAL() { return GetToken(AgiilQueryParser.GREATERTHANOREQUAL, 0); }
		public ITerminalNode LESSTHANOREQUAL() { return GetToken(AgiilQueryParser.LESSTHANOREQUAL, 0); }
		public ComparisonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparison; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparison(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ComparisonContext comparison() {
		ComparisonContext _localctx = new ComparisonContext(Context, State);
		EnterRule(_localctx, 22, RULE_comparison);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << GREATERTHAN) | (1L << LESSTHAN) | (1L << GREATERTHANOREQUAL) | (1L << LESSTHANOREQUAL))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public ConstantvalueContext constantvalue() {
			return GetRuleContext<ConstantvalueContext>(0);
		}
		public FunctioninvocationContext functioninvocation() {
			return GetRuleContext<FunctioninvocationContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 24, RULE_value);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				State = 97; constantvalue();
				}
				break;
			case 2:
				{
				State = 98; functioninvocation();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstantvalueContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(AgiilQueryParser.NAME, 0); }
		public ITerminalNode NOT() { return GetToken(AgiilQueryParser.NOT, 0); }
		public ITerminalNode AND() { return GetToken(AgiilQueryParser.AND, 0); }
		public ITerminalNode OR() { return GetToken(AgiilQueryParser.OR, 0); }
		public ITerminalNode DESCENDING() { return GetToken(AgiilQueryParser.DESCENDING, 0); }
		public ITerminalNode ASCENDING() { return GetToken(AgiilQueryParser.ASCENDING, 0); }
		public ITerminalNode QUOTEDVALUE() { return GetToken(AgiilQueryParser.QUOTEDVALUE, 0); }
		public ITerminalNode[] WORD() { return GetTokens(AgiilQueryParser.WORD); }
		public ITerminalNode WORD(int i) {
			return GetToken(AgiilQueryParser.WORD, i);
		}
		public ConstantvalueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constantvalue; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstantvalue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConstantvalueContext constantvalue() {
		ConstantvalueContext _localctx = new ConstantvalueContext(Context, State);
		EnterRule(_localctx, 26, RULE_constantvalue);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NAME:
				{
				State = 101; Match(NAME);
				}
				break;
			case NOT:
				{
				State = 102; Match(NOT);
				}
				break;
			case AND:
				{
				State = 103; Match(AND);
				}
				break;
			case OR:
				{
				State = 104; Match(OR);
				}
				break;
			case WORD:
				{
				State = 106;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 105; Match(WORD);
					}
					}
					State = 108;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==WORD );
				}
				break;
			case DESCENDING:
				{
				State = 110; Match(DESCENDING);
				}
				break;
			case ASCENDING:
				{
				State = 111; Match(ASCENDING);
				}
				break;
			case QUOTEDVALUE:
				{
				State = 112; Match(QUOTEDVALUE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctioninvocationContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(AgiilQueryParser.NAME, 0); }
		public ITerminalNode OPENPAREN() { return GetToken(AgiilQueryParser.OPENPAREN, 0); }
		public FunctionparametersContext functionparameters() {
			return GetRuleContext<FunctionparametersContext>(0);
		}
		public ITerminalNode CLOSEPAREN() { return GetToken(AgiilQueryParser.CLOSEPAREN, 0); }
		public FunctioninvocationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functioninvocation; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctioninvocation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctioninvocationContext functioninvocation() {
		FunctioninvocationContext _localctx = new FunctioninvocationContext(Context, State);
		EnterRule(_localctx, 28, RULE_functioninvocation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 115; Match(NAME);
			State = 116; Match(OPENPAREN);
			State = 117; functionparameters();
			State = 118; Match(CLOSEPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionparametersContext : ParserRuleContext {
		public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(AgiilQueryParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(AgiilQueryParser.COMMA, i);
		}
		public FunctionparametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionparameters; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionparameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionparametersContext functionparameters() {
		FunctionparametersContext _localctx = new FunctionparametersContext(Context, State);
		EnterRule(_localctx, 30, RULE_functionparameters);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NOT) | (1L << AND) | (1L << OR) | (1L << DESCENDING) | (1L << ASCENDING) | (1L << NAME) | (1L << WORD) | (1L << QUOTEDVALUE))) != 0)) {
				{
				State = 120; value();
				State = 125;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 121; Match(COMMA);
					State = 122; value();
					}
					}
					State = 127;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrdersContext : ParserRuleContext {
		public ITerminalNode ORDERBY() { return GetToken(AgiilQueryParser.ORDERBY, 0); }
		public OrderelementContext[] orderelement() {
			return GetRuleContexts<OrderelementContext>();
		}
		public OrderelementContext orderelement(int i) {
			return GetRuleContext<OrderelementContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(AgiilQueryParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(AgiilQueryParser.COMMA, i);
		}
		public OrdersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_orders; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrders(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrdersContext orders() {
		OrdersContext _localctx = new OrdersContext(Context, State);
		EnterRule(_localctx, 32, RULE_orders);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130; Match(ORDERBY);
			State = 131; orderelement();
			State = 136;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 132; Match(COMMA);
				State = 133; orderelement();
				}
				}
				State = 138;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrderelementContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(AgiilQueryParser.NAME, 0); }
		public FunctioninvocationContext functioninvocation() {
			return GetRuleContext<FunctioninvocationContext>(0);
		}
		public ITerminalNode ASCENDING() { return GetToken(AgiilQueryParser.ASCENDING, 0); }
		public ITerminalNode DESCENDING() { return GetToken(AgiilQueryParser.DESCENDING, 0); }
		public OrderelementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_orderelement; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAgiilQueryVisitor<TResult> typedVisitor = visitor as IAgiilQueryVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrderelement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrderelementContext orderelement() {
		OrderelementContext _localctx = new OrderelementContext(Context, State);
		EnterRule(_localctx, 34, RULE_orderelement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 141;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				{
				State = 139; Match(NAME);
				}
				break;
			case 2:
				{
				State = 140; functioninvocation();
				}
				break;
			}
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DESCENDING || _la==ASCENDING) {
				{
				State = 143;
				_la = TokenStream.LA(1);
				if ( !(_la==DESCENDING || _la==ASCENDING) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x19', '\x95', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\x5', '\x2', '(', '\n', '\x2', '\x3', '\x2', '\x5', 
		'\x2', '+', '\n', '\x2', '\x3', '\x2', '\x5', '\x2', '.', '\n', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x5', '\x4', '\x36', '\n', '\x4', '\x3', '\x4', '\a', '\x4', 
		'\x39', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '<', '\v', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x5', '\x5', '@', '\n', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', 'M', 
		'\n', '\b', '\x3', '\b', '\x5', '\b', 'P', '\n', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x5', '\v', 'W', '\n', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x5', '\f', '`', '\n', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x5', '\xE', '\x66', '\n', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x6', 
		'\xF', 'm', '\n', '\xF', '\r', '\xF', '\xE', '\xF', 'n', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x5', '\xF', 't', '\n', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\a', '\x11', '~', '\n', '\x11', '\f', '\x11', 
		'\xE', '\x11', '\x81', '\v', '\x11', '\x5', '\x11', '\x83', '\n', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', 
		'\x89', '\n', '\x12', '\f', '\x12', '\xE', '\x12', '\x8C', '\v', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\x90', '\n', '\x13', '\x3', 
		'\x13', '\x5', '\x13', '\x93', '\n', '\x13', '\x3', '\x13', '\x2', '\x2', 
		'\x14', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '\x2', 
		'\x5', '\x3', '\x2', '\x11', '\x12', '\x3', '\x2', '\v', '\xE', '\x3', 
		'\x2', '\x14', '\x15', '\x2', '\x9D', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x4', '\x31', '\x3', '\x2', '\x2', '\x2', '\x6', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\b', '?', '\x3', '\x2', '\x2', '\x2', '\n', '\x41', 
		'\x3', '\x2', '\x2', '\x2', '\f', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\xE', 'O', '\x3', '\x2', '\x2', '\x2', '\x10', 'Q', '\x3', '\x2', '\x2', 
		'\x2', '\x12', 'S', '\x3', '\x2', '\x2', '\x2', '\x14', 'V', '\x3', '\x2', 
		'\x2', '\x2', '\x16', '_', '\x3', '\x2', '\x2', '\x2', '\x18', '\x61', 
		'\x3', '\x2', '\x2', '\x2', '\x1A', '\x65', '\x3', '\x2', '\x2', '\x2', 
		'\x1C', 's', '\x3', '\x2', '\x2', '\x2', '\x1E', 'u', '\x3', '\x2', '\x2', 
		'\x2', ' ', '\x82', '\x3', '\x2', '\x2', '\x2', '\"', '\x84', '\x3', '\x2', 
		'\x2', '\x2', '$', '\x8F', '\x3', '\x2', '\x2', '\x2', '&', '(', '\a', 
		'\x3', '\x2', '\x2', '\'', '&', '\x3', '\x2', '\x2', '\x2', '\'', '(', 
		'\x3', '\x2', '\x2', '\x2', '(', '*', '\x3', '\x2', '\x2', '\x2', ')', 
		'+', '\x5', '\x4', '\x3', '\x2', '*', ')', '\x3', '\x2', '\x2', '\x2', 
		'*', '+', '\x3', '\x2', '\x2', '\x2', '+', '-', '\x3', '\x2', '\x2', '\x2', 
		',', '.', '\x5', '\"', '\x12', '\x2', '-', ',', '\x3', '\x2', '\x2', '\x2', 
		'-', '.', '\x3', '\x2', '\x2', '\x2', '.', '/', '\x3', '\x2', '\x2', '\x2', 
		'/', '\x30', '\a', '\x2', '\x2', '\x3', '\x30', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x32', '\x5', '\x6', '\x4', '\x2', '\x32', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x33', ':', '\x5', '\b', '\x5', '\x2', '\x34', '\x36', 
		'\x5', '\x10', '\t', '\x2', '\x35', '\x34', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x36', '\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\x39', '\x5', '\b', '\x5', '\x2', '\x38', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x39', '<', '\x3', '\x2', '\x2', '\x2', ':', 
		'\x38', '\x3', '\x2', '\x2', '\x2', ':', ';', '\x3', '\x2', '\x2', '\x2', 
		';', '\a', '\x3', '\x2', '\x2', '\x2', '<', ':', '\x3', '\x2', '\x2', 
		'\x2', '=', '@', '\x5', '\f', '\a', '\x2', '>', '@', '\x5', '\n', '\x6', 
		'\x2', '?', '=', '\x3', '\x2', '\x2', '\x2', '?', '>', '\x3', '\x2', '\x2', 
		'\x2', '@', '\t', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\x4', 
		'\x2', '\x2', '\x42', '\x43', '\x5', '\x6', '\x4', '\x2', '\x43', '\x44', 
		'\a', '\x5', '\x2', '\x2', '\x44', '\v', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\x5', '\x12', '\n', '\x2', '\x46', 'G', '\x5', '\xE', '\b', '\x2', 
		'G', '\r', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\x5', '\x14', '\v', 
		'\x2', 'I', 'J', '\x5', '\x1A', '\xE', '\x2', 'J', 'P', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'M', '\a', '\x10', '\x2', '\x2', 'L', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'L', 'M', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'P', '\x5', '\x1E', '\x10', '\x2', 'O', 'H', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'L', '\x3', '\x2', '\x2', '\x2', 'P', '\xF', 
		'\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\t', '\x2', '\x2', '\x2', 'R', 
		'\x11', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '\x16', '\x2', '\x2', 
		'T', '\x13', '\x3', '\x2', '\x2', '\x2', 'U', 'W', '\a', '\x10', '\x2', 
		'\x2', 'V', 'U', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\x5', '\x16', 
		'\f', '\x2', 'Y', '\x15', '\x3', '\x2', '\x2', '\x2', 'Z', '`', '\a', 
		'\x6', '\x2', '\x2', '[', '`', '\a', '\a', '\x2', '\x2', '\\', '`', '\a', 
		'\b', '\x2', '\x2', ']', '`', '\a', '\x16', '\x2', '\x2', '^', '`', '\x5', 
		'\x18', '\r', '\x2', '_', 'Z', '\x3', '\x2', '\x2', '\x2', '_', '[', '\x3', 
		'\x2', '\x2', '\x2', '_', '\\', '\x3', '\x2', '\x2', '\x2', '_', ']', 
		'\x3', '\x2', '\x2', '\x2', '_', '^', '\x3', '\x2', '\x2', '\x2', '`', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\t', '\x3', '\x2', 
		'\x2', '\x62', '\x19', '\x3', '\x2', '\x2', '\x2', '\x63', '\x66', '\x5', 
		'\x1C', '\xF', '\x2', '\x64', '\x66', '\x5', '\x1E', '\x10', '\x2', '\x65', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x65', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x66', '\x1B', '\x3', '\x2', '\x2', '\x2', 'g', 't', '\a', '\x16', 
		'\x2', '\x2', 'h', 't', '\a', '\x10', '\x2', '\x2', 'i', 't', '\a', '\x11', 
		'\x2', '\x2', 'j', 't', '\a', '\x12', '\x2', '\x2', 'k', 'm', '\a', '\x17', 
		'\x2', '\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', 
		'\x2', '\x2', 'o', 't', '\x3', '\x2', '\x2', '\x2', 'p', 't', '\a', '\x14', 
		'\x2', '\x2', 'q', 't', '\a', '\x15', '\x2', '\x2', 'r', 't', '\a', '\x18', 
		'\x2', '\x2', 's', 'g', '\x3', '\x2', '\x2', '\x2', 's', 'h', '\x3', '\x2', 
		'\x2', '\x2', 's', 'i', '\x3', '\x2', '\x2', '\x2', 's', 'j', '\x3', '\x2', 
		'\x2', '\x2', 's', 'l', '\x3', '\x2', '\x2', '\x2', 's', 'p', '\x3', '\x2', 
		'\x2', '\x2', 's', 'q', '\x3', '\x2', '\x2', '\x2', 's', 'r', '\x3', '\x2', 
		'\x2', '\x2', 't', '\x1D', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', 
		'\x16', '\x2', '\x2', 'v', 'w', '\a', '\x4', '\x2', '\x2', 'w', 'x', '\x5', 
		' ', '\x11', '\x2', 'x', 'y', '\a', '\x5', '\x2', '\x2', 'y', '\x1F', 
		'\x3', '\x2', '\x2', '\x2', 'z', '\x7F', '\x5', '\x1A', '\xE', '\x2', 
		'{', '|', '\a', '\t', '\x2', '\x2', '|', '~', '\x5', '\x1A', '\xE', '\x2', 
		'}', '{', '\x3', '\x2', '\x2', '\x2', '~', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '}', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '\x83', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x7F', '\x3', '\x2', '\x2', '\x2', '\x82', 'z', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x85', '\a', '\x13', '\x2', '\x2', '\x85', 
		'\x8A', '\x5', '$', '\x13', '\x2', '\x86', '\x87', '\a', '\t', '\x2', 
		'\x2', '\x87', '\x89', '\x5', '$', '\x13', '\x2', '\x88', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '#', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8A', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x90', '\a', '\x16', '\x2', '\x2', '\x8E', 
		'\x90', '\x5', '\x1E', '\x10', '\x2', '\x8F', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x93', '\t', '\x4', '\x2', '\x2', '\x92', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '%', '\x3', '\x2', '\x2', '\x2', '\x14', '\'', '*', '-', 
		'\x35', ':', '?', 'L', 'O', 'V', '_', '\x65', 'n', 's', '\x7F', '\x82', 
		'\x8A', '\x8F', '\x92',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Agiil.QueryLanguage
