//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/craig/Projects/Agiil/Agiil.QueryLanguage.Antlr/AgiilQuery.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Agiil.QueryLanguage {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class AgiilQueryLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BOM=1, OPENPAREN=2, CLOSEPAREN=3, EQUALS=4, NOTEQUALS=5, TILDE=6, COMMA=7, 
		DOUBLEQUOTE=8, WHITESPACE=9, NOT=10, AND=11, OR=12, ORDERBY=13, DESCENDING=14, 
		ASCENDING=15, NAME=16, WORD=17, QUOTEDVALUE=18, ANY=19;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"A", "B", "C", "D", "E", "G", "H", "I", "K", "L", "N", "O", "R", "S", 
		"T", "Y", "UPPERCASE", "LOWERCASE", "DIGIT", "BOM", "OPENPAREN", "CLOSEPAREN", 
		"EQUALS", "NOTEQUALS", "TILDE", "COMMA", "DOUBLEQUOTE", "WHITESPACE", 
		"NOT", "AND", "OR", "ORDERBY", "DESCENDING", "ASCENDING", "NAME", "WORD", 
		"QUOTEDVALUE", "ANY"
	};


	public AgiilQueryLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public AgiilQueryLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'\uFEFF'", "'('", "')'", "'='", "'!='", "'~'", "','", "'\"'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BOM", "OPENPAREN", "CLOSEPAREN", "EQUALS", "NOTEQUALS", "TILDE", 
		"COMMA", "DOUBLEQUOTE", "WHITESPACE", "NOT", "AND", "OR", "ORDERBY", "DESCENDING", 
		"ASCENDING", "NAME", "WORD", "QUOTEDVALUE", "ANY"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "AgiilQuery.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static AgiilQueryLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x15', '\xD7', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', 
		'\x5', '\x1D', '\x8B', '\n', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', ' ', 
		'\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', 
		'\x3', '!', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '\"', 
		'\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', 
		'\"', '\x3', '\"', '\x3', '\"', '\x5', '\"', '\xAE', '\n', '\"', '\x3', 
		'#', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', 
		'#', '\x3', '#', '\x3', '#', '\x3', '#', '\x5', '#', '\xBA', '\n', '#', 
		'\x3', '$', '\x3', '$', '\x3', '$', '\x5', '$', '\xBF', '\n', '$', '\x3', 
		'$', '\x3', '$', '\x3', '$', '\x3', '$', '\x6', '$', '\xC5', '\n', '$', 
		'\r', '$', '\xE', '$', '\xC6', '\x3', '%', '\x3', '%', '\x3', '&', '\x3', 
		'&', '\x3', '&', '\x3', '&', '\a', '&', '\xCF', '\n', '&', '\f', '&', 
		'\xE', '&', '\xD2', '\v', '&', '\x3', '&', '\x3', '&', '\x3', '\'', '\x3', 
		'\'', '\x2', '\x2', '(', '\x3', '\x2', '\x5', '\x2', '\a', '\x2', '\t', 
		'\x2', '\v', '\x2', '\r', '\x2', '\xF', '\x2', '\x11', '\x2', '\x13', 
		'\x2', '\x15', '\x2', '\x17', '\x2', '\x19', '\x2', '\x1B', '\x2', '\x1D', 
		'\x2', '\x1F', '\x2', '!', '\x2', '#', '\x2', '%', '\x2', '\'', '\x2', 
		')', '\x3', '+', '\x4', '-', '\x5', '/', '\x6', '\x31', '\a', '\x33', 
		'\b', '\x35', '\t', '\x37', '\n', '\x39', '\v', ';', '\f', '=', '\r', 
		'?', '\xE', '\x41', '\xF', '\x43', '\x10', '\x45', '\x11', 'G', '\x12', 
		'I', '\x13', 'K', '\x14', 'M', '\x15', '\x3', '\x2', '\x18', '\x4', '\x2', 
		'\x43', '\x43', '\x63', '\x63', '\x4', '\x2', '\x44', '\x44', '\x64', 
		'\x64', '\x4', '\x2', '\x45', '\x45', '\x65', '\x65', '\x4', '\x2', '\x46', 
		'\x46', '\x66', '\x66', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', 
		'I', 'I', 'i', 'i', '\x4', '\x2', 'J', 'J', 'j', 'j', '\x4', '\x2', 'K', 
		'K', 'k', 'k', '\x4', '\x2', 'M', 'M', 'm', 'm', '\x4', '\x2', 'N', 'N', 
		'n', 'n', '\x4', '\x2', 'P', 'P', 'p', 'p', '\x4', '\x2', 'Q', 'Q', 'q', 
		'q', '\x4', '\x2', 'T', 'T', 't', 't', '\x4', '\x2', 'U', 'U', 'u', 'u', 
		'\x4', '\x2', 'V', 'V', 'v', 'v', '\x4', '\x2', '[', '[', '{', '{', '\x3', 
		'\x2', '\x43', '\\', '\x3', '\x2', '\x63', '|', '\x3', '\x2', '\x32', 
		';', '\x4', '\x2', '\v', '\v', '\"', '\"', '\t', '\x2', '\v', '\f', '\xF', 
		'\xF', '\"', '#', '*', '+', '.', '.', '?', '?', '\x80', '\x80', '\x4', 
		'\x2', '$', '$', '^', '^', '\x2', '\xCF', '\x2', ')', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x43', '\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x2', 'M', '\x3', 
		'\x2', '\x2', '\x2', '\x3', 'O', '\x3', '\x2', '\x2', '\x2', '\x5', 'Q', 
		'\x3', '\x2', '\x2', '\x2', '\a', 'S', '\x3', '\x2', '\x2', '\x2', '\t', 
		'U', '\x3', '\x2', '\x2', '\x2', '\v', 'W', '\x3', '\x2', '\x2', '\x2', 
		'\r', 'Y', '\x3', '\x2', '\x2', '\x2', '\xF', '[', '\x3', '\x2', '\x2', 
		'\x2', '\x11', ']', '\x3', '\x2', '\x2', '\x2', '\x13', '_', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\x61', '\x3', '\x2', '\x2', '\x2', '\x17', '\x63', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\x65', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', 'g', '\x3', '\x2', '\x2', '\x2', '\x1D', 'i', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', 'k', '\x3', '\x2', '\x2', '\x2', '!', 'm', '\x3', '\x2', 
		'\x2', '\x2', '#', 'o', '\x3', '\x2', '\x2', '\x2', '%', 'q', '\x3', '\x2', 
		'\x2', '\x2', '\'', 's', '\x3', '\x2', '\x2', '\x2', ')', 'u', '\x3', 
		'\x2', '\x2', '\x2', '+', 'w', '\x3', '\x2', '\x2', '\x2', '-', 'y', '\x3', 
		'\x2', '\x2', '\x2', '/', '{', '\x3', '\x2', '\x2', '\x2', '\x31', '}', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x82', '\x3', '\x2', '\x2', '\x2', '\x37', '\x84', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\x8A', '\x3', '\x2', '\x2', '\x2', ';', '\x8E', 
		'\x3', '\x2', '\x2', '\x2', '=', '\x92', '\x3', '\x2', '\x2', '\x2', '?', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x41', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\xA2', '\x3', '\x2', '\x2', '\x2', '\x45', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', 'G', '\xBE', '\x3', '\x2', '\x2', '\x2', 'I', '\xC8', 
		'\x3', '\x2', '\x2', '\x2', 'K', '\xCA', '\x3', '\x2', '\x2', '\x2', 'M', 
		'\xD5', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\t', '\x2', '\x2', '\x2', 
		'P', '\x4', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\t', '\x3', '\x2', 
		'\x2', 'R', '\x6', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\t', '\x4', 
		'\x2', '\x2', 'T', '\b', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\t', '\x5', 
		'\x2', '\x2', 'V', '\n', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\t', '\x6', 
		'\x2', '\x2', 'X', '\f', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\t', '\a', 
		'\x2', '\x2', 'Z', '\xE', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\t', 
		'\b', '\x2', '\x2', '\\', '\x10', '\x3', '\x2', '\x2', '\x2', ']', '^', 
		'\t', '\t', '\x2', '\x2', '^', '\x12', '\x3', '\x2', '\x2', '\x2', '_', 
		'`', '\t', '\n', '\x2', '\x2', '`', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'\x61', '\x62', '\t', '\v', '\x2', '\x2', '\x62', '\x16', '\x3', '\x2', 
		'\x2', '\x2', '\x63', '\x64', '\t', '\f', '\x2', '\x2', '\x64', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\t', '\r', '\x2', '\x2', 
		'\x66', '\x1A', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\t', '\xE', '\x2', 
		'\x2', 'h', '\x1C', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\t', '\xF', 
		'\x2', '\x2', 'j', '\x1E', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\t', 
		'\x10', '\x2', '\x2', 'l', ' ', '\x3', '\x2', '\x2', '\x2', 'm', 'n', 
		'\t', '\x11', '\x2', '\x2', 'n', '\"', '\x3', '\x2', '\x2', '\x2', 'o', 
		'p', '\t', '\x12', '\x2', '\x2', 'p', '$', '\x3', '\x2', '\x2', '\x2', 
		'q', 'r', '\t', '\x13', '\x2', '\x2', 'r', '&', '\x3', '\x2', '\x2', '\x2', 
		's', 't', '\t', '\x14', '\x2', '\x2', 't', '(', '\x3', '\x2', '\x2', '\x2', 
		'u', 'v', '\a', '\xFF01', '\x2', '\x2', 'v', '*', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\a', '*', '\x2', '\x2', 'x', ',', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'z', '\a', '+', '\x2', '\x2', 'z', '.', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\a', '?', '\x2', '\x2', '|', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\a', '#', '\x2', '\x2', '~', '\x7F', '\a', '?', '\x2', 
		'\x2', '\x7F', '\x32', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\a', 
		'\x80', '\x2', '\x2', '\x81', '\x34', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x83', '\a', '.', '\x2', '\x2', '\x83', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x85', '\a', '$', '\x2', '\x2', '\x85', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x8B', '\t', '\x15', '\x2', '\x2', '\x87', 
		'\x88', '\a', '\xF', '\x2', '\x2', '\x88', '\x8B', '\a', '\f', '\x2', 
		'\x2', '\x89', '\x8B', '\a', '\f', '\x2', '\x2', '\x8A', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x8A', '\x87', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8C', '\x8D', '\b', '\x1D', '\x2', '\x2', '\x8D', ':', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x8F', '\x5', '\x17', '\f', '\x2', '\x8F', 
		'\x90', '\x5', '\x19', '\r', '\x2', '\x90', '\x91', '\x5', '\x1F', '\x10', 
		'\x2', '\x91', '<', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\x5', 
		'\x3', '\x2', '\x2', '\x93', '\x94', '\x5', '\x17', '\f', '\x2', '\x94', 
		'\x95', '\x5', '\t', '\x5', '\x2', '\x95', '>', '\x3', '\x2', '\x2', '\x2', 
		'\x96', '\x97', '\x5', '\x19', '\r', '\x2', '\x97', '\x98', '\x5', '\x1B', 
		'\xE', '\x2', '\x98', '@', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', 
		'\x5', '\x19', '\r', '\x2', '\x9A', '\x9B', '\x5', '\x1B', '\xE', '\x2', 
		'\x9B', '\x9C', '\x5', '\t', '\x5', '\x2', '\x9C', '\x9D', '\x5', '\v', 
		'\x6', '\x2', '\x9D', '\x9E', '\x5', '\x1B', '\xE', '\x2', '\x9E', '\x9F', 
		'\a', '\"', '\x2', '\x2', '\x9F', '\xA0', '\x5', '\x5', '\x3', '\x2', 
		'\xA0', '\xA1', '\x5', '!', '\x11', '\x2', '\xA1', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\xA2', '\xA3', '\x5', '\t', '\x5', '\x2', '\xA3', '\xA4', 
		'\x5', '\v', '\x6', '\x2', '\xA4', '\xA5', '\x5', '\x1D', '\xF', '\x2', 
		'\xA5', '\xAD', '\x5', '\a', '\x4', '\x2', '\xA6', '\xA7', '\x5', '\v', 
		'\x6', '\x2', '\xA7', '\xA8', '\x5', '\x17', '\f', '\x2', '\xA8', '\xA9', 
		'\x5', '\t', '\x5', '\x2', '\xA9', '\xAA', '\x5', '\x11', '\t', '\x2', 
		'\xAA', '\xAB', '\x5', '\x17', '\f', '\x2', '\xAB', '\xAC', '\x5', '\r', 
		'\a', '\x2', '\xAC', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', '\x2', '\x2', '\x2', 
		'\xAE', '\x44', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB0', '\x5', '\x3', 
		'\x2', '\x2', '\xB0', '\xB1', '\x5', '\x1D', '\xF', '\x2', '\xB1', '\xB9', 
		'\x5', '\a', '\x4', '\x2', '\xB2', '\xB3', '\x5', '\v', '\x6', '\x2', 
		'\xB3', '\xB4', '\x5', '\x17', '\f', '\x2', '\xB4', '\xB5', '\x5', '\t', 
		'\x5', '\x2', '\xB5', '\xB6', '\x5', '\x11', '\t', '\x2', '\xB6', '\xB7', 
		'\x5', '\x17', '\f', '\x2', '\xB7', '\xB8', '\x5', '\r', '\a', '\x2', 
		'\xB8', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB2', '\x3', '\x2', 
		'\x2', '\x2', '\xB9', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', '\x46', 
		'\x3', '\x2', '\x2', '\x2', '\xBB', '\xBF', '\x5', '#', '\x12', '\x2', 
		'\xBC', '\xBF', '\x5', '%', '\x13', '\x2', '\xBD', '\xBF', '\a', '\x61', 
		'\x2', '\x2', '\xBE', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBC', 
		'\x3', '\x2', '\x2', '\x2', '\xBE', '\xBD', '\x3', '\x2', '\x2', '\x2', 
		'\xBF', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC5', '\x5', '#', 
		'\x12', '\x2', '\xC1', '\xC5', '\x5', '%', '\x13', '\x2', '\xC2', '\xC5', 
		'\a', '\x61', '\x2', '\x2', '\xC3', '\xC5', '\x5', '\'', '\x14', '\x2', 
		'\xC4', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC1', '\x3', '\x2', 
		'\x2', '\x2', '\xC4', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC3', 
		'\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', '\x3', '\x2', '\x2', '\x2', 
		'\xC6', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', '\x2', 
		'\x2', '\x2', '\xC7', 'H', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC9', 
		'\n', '\x16', '\x2', '\x2', '\xC9', 'J', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\xD0', '\a', '$', '\x2', '\x2', '\xCB', '\xCF', '\n', '\x17', '\x2', 
		'\x2', '\xCC', '\xCD', '\a', '^', '\x2', '\x2', '\xCD', '\xCF', '\t', 
		'\x17', '\x2', '\x2', '\xCE', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCE', 
		'\xCC', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD2', '\x3', '\x2', '\x2', 
		'\x2', '\xD0', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD2', 
		'\xD0', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\a', '$', '\x2', 
		'\x2', '\xD4', 'L', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD6', '\v', 
		'\x2', '\x2', '\x2', '\xD6', 'N', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', 
		'\x8A', '\xAD', '\xB9', '\xBE', '\xC4', '\xC6', '\xCE', '\xD0', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Agiil.QueryLanguage
